name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test:unit